version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      gradle:
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps)"
