package eu.hxreborn.gplayadblock.discovery

sealed interface ResolvedTargets {
    data class Resolved(
        val streamDataMethod: MethodRef,
        val streamChildrenField: FieldRef,
        val childHandlersField: FieldRef,
        val childIdField: FieldRef,
        val nodeField: FieldRef,
        val presentationAccessor: MethodRef,
        val presentationKindField: FieldRef,
        val presentationPayloadField: FieldRef,
        val clusterCaseField: FieldRef,
        val clusterPayloadField: FieldRef,
        val clusterServerLogsField: FieldRef,
        val cardKindField: FieldRef,
        val cardPayloadField: FieldRef,
        val cardAdMetadataFields: List<FieldRef>,
        val adPresenceField: FieldRef,
        val responseMethods: List<MethodRef>,
        val responseListFields: List<FieldRef>,
        val nodeWrapperKindField: FieldRef,
        val nodeWrapperPayloadField: FieldRef,
        val nodeIdField: FieldRef,
        val nodePresentationField: FieldRef,
        val nodeChildrenField: FieldRef,
        val rootWrapperKindField: FieldRef,
        val rootWrapperPayloadField: FieldRef,
        val rootChildrenField: FieldRef,
        val childIdsField: FieldRef,
        val childPresenceField: FieldRef,
        val childContinuationField: FieldRef,
        val nodeDefaultInstanceField: FieldRef,
        val rootDefaultInstanceField: FieldRef,
        val cacheAssemblyMethod: MethodRef,
        val cacheNodeChildrenField: FieldRef,
        val cachePageBoundariesField: FieldRef,
        val cachePageBoundariesCopyMethod: MethodRef,
        val childKeyMethod: MethodRef,
        val protobufNewBuilderMethod: MethodRef,
        val protobufMergeMethod: MethodRef,
        val protobufBuildMethod: MethodRef,
        val protobufBuilderMessageField: FieldRef,
        val protobufParseMethod: MethodRef,
        val protobufRegistryFactory: MethodRef,
        val byteStringToByteArrayMethod: MethodRef,
        val protobufToByteArrayMethod: MethodRef,
        val repeatedListCopyMethod: MethodRef,
        val searchSuggestionConstructor: ConstructorRef,
        val suggestionAdInfoField: FieldRef,
    ) : ResolvedTargets

    data class Missing(
        val reason: String,
    ) : ResolvedTargets
}
